<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="9" ignored="0" total="20" passed="11">
  <reporter-output>
  </reporter-output>
  <suite name="Chrome" duration-ms="367462" started-at="2019-09-13T07:47:20Z" finished-at="2019-09-13T07:53:27Z">
    <groups>
    </groups>
    <test name="Chrome" duration-ms="367462" started-at="2019-09-13T07:47:20Z" finished-at="2019-09-13T07:53:27Z">
      <class name="Stepdef.Spalding_Login">
        <test-method status="PASS" signature="i_am_a_registered_user_of_spalding_and_I_open_a_browser(java.lang.String)[pri:6, instance:Stepdef.Spalding_Login@eec5a4a]" name="i_am_a_registered_user_of_spalding_and_I_open_a_browser" duration-ms="940" started-at="2019-09-13T07:49:42Z" finished-at="2019-09-13T07:49:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_am_a_registered_user_of_spalding_and_I_open_a_browser -->
        <test-method status="PASS" signature="i_navigate_to_a_premium_article_on_spalding()[pri:7, instance:Stepdef.Spalding_Login@eec5a4a]" name="i_navigate_to_a_premium_article_on_spalding" duration-ms="12321" started-at="2019-09-13T07:49:43Z" finished-at="2019-09-13T07:49:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_navigate_to_a_premium_article_on_spalding -->
        <test-method status="PASS" signature="i_click_on_Login_from_spalding_First_use_notice()[pri:8, instance:Stepdef.Spalding_Login@eec5a4a]" name="i_click_on_Login_from_spalding_First_use_notice" duration-ms="21097" started-at="2019-09-13T07:49:55Z" finished-at="2019-09-13T07:50:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_click_on_Login_from_spalding_First_use_notice -->
        <test-method status="PASS" signature="i_verify_that_the_Login_Button_Navigates_me_to_the_login_page_to_log_me_in_to_spalding()[pri:9, instance:Stepdef.Spalding_Login@eec5a4a]" name="i_verify_that_the_Login_Button_Navigates_me_to_the_login_page_to_log_me_in_to_spalding" duration-ms="10300" started-at="2019-09-13T07:50:16Z" finished-at="2019-09-13T07:50:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_verify_that_the_Login_Button_Navigates_me_to_the_login_page_to_log_me_in_to_spalding -->
        <test-method status="PASS" signature="entering_the_correct_email_and_password_logs_me_in_to_spalding()[pri:10, instance:Stepdef.Spalding_Login@eec5a4a]" name="entering_the_correct_email_and_password_logs_me_in_to_spalding" duration-ms="6875" started-at="2019-09-13T07:50:26Z" finished-at="2019-09-13T07:50:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- entering_the_correct_email_and_password_logs_me_in_to_spalding -->
        <test-method status="FAIL" signature="verify_that_I_am_being_navigated_to_the_same_article_on_spalding()[pri:11, instance:Stepdef.Spalding_Login@eec5a4a]" name="verify_that_I_am_being_navigated_to_the_same_article_on_spalding" duration-ms="5088" started-at="2019-09-13T07:50:33Z" finished-at="2019-09-13T07:50:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<0.2> but was:<-0.2>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<0.2> but was:<-0.2>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Spalding_Login.verify_that_I_am_being_navigated_to_the_same_article_on_spalding(Spalding_Login.java:179)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_that_I_am_being_navigated_to_the_same_article_on_spalding -->
      </class> <!-- Stepdef.Spalding_Login -->
      <class name="Stepdef.Spalding_transaction">
        <test-method status="PASS" signature="i_am_a_registered_Agate_User_and_I_login_in_to_spalding(java.lang.String)[pri:12, instance:Stepdef.Spalding_transaction@2b2948e2]" name="i_am_a_registered_Agate_User_and_I_login_in_to_spalding" duration-ms="68131" started-at="2019-09-13T07:50:38Z" finished-at="2019-09-13T07:51:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_am_a_registered_Agate_User_and_I_login_in_to_spalding -->
        <test-method status="FAIL" signature="i_read_a_premium_article_on_spalding()[pri:13, instance:Stepdef.Spalding_transaction@2b2948e2]" name="i_read_a_premium_article_on_spalding" duration-ms="14644" started-at="2019-09-13T07:51:46Z" finished-at="2019-09-13T07:52:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<0.2> but was:<-0.4>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<0.2> but was:<-0.4>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Spalding_transaction.i_read_a_premium_article_on_spalding(Spalding_transaction.java:137)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_read_a_premium_article_on_spalding -->
        <test-method status="FAIL" signature="the_popbitch_wallet_balance_is_updated_same_as_spalding_and_free_point_remains_uneffected()[pri:14, instance:Stepdef.Spalding_transaction@2b2948e2]" name="the_popbitch_wallet_balance_is_updated_same_as_spalding_and_free_point_remains_uneffected" duration-ms="14480" started-at="2019-09-13T07:52:01Z" finished-at="2019-09-13T07:52:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<9.4> but was:<10.0>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<9.4> but was:<10.0>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Spalding_transaction.the_popbitch_wallet_balance_is_updated_same_as_spalding_and_free_point_remains_uneffected(Spalding_transaction.java:177)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- the_popbitch_wallet_balance_is_updated_same_as_spalding_and_free_point_remains_uneffected -->
        <test-method status="FAIL" signature="reaction_wallet_balance_is_updated_and_free_point_remains_uneffected_same_as_spalding()[pri:15, instance:Stepdef.Spalding_transaction@2b2948e2]" name="reaction_wallet_balance_is_updated_and_free_point_remains_uneffected_same_as_spalding" duration-ms="14555" started-at="2019-09-13T07:52:16Z" finished-at="2019-09-13T07:52:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<9.4> but was:<10.0>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<9.4> but was:<10.0>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Spalding_transaction.reaction_wallet_balance_is_updated_and_free_point_remains_uneffected_same_as_spalding(Spalding_transaction.java:217)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reaction_wallet_balance_is_updated_and_free_point_remains_uneffected_same_as_spalding -->
        <test-method status="FAIL" signature="cricketer_wallet_balance_remains_and_is_uneffected_by_spalding()[pri:16, instance:Stepdef.Spalding_transaction@2b2948e2]" name="cricketer_wallet_balance_remains_and_is_uneffected_by_spalding" duration-ms="13694" started-at="2019-09-13T07:52:30Z" finished-at="2019-09-13T07:52:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<9.4> but was:<10.0>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<9.4> but was:<10.0>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Spalding_transaction.cricketer_wallet_balance_remains_and_is_uneffected_by_spalding(Spalding_transaction.java:258)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cricketer_wallet_balance_remains_and_is_uneffected_by_spalding -->
        <test-method status="FAIL" signature="cornwall_wallet_balance_remains_and_is_uneffected_by_spalding()[pri:17, instance:Stepdef.Spalding_transaction@2b2948e2]" name="cornwall_wallet_balance_remains_and_is_uneffected_by_spalding" duration-ms="14283" started-at="2019-09-13T07:52:44Z" finished-at="2019-09-13T07:52:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<9.4> but was:<10.0>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<9.4> but was:<10.0>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Spalding_transaction.cornwall_wallet_balance_remains_and_is_uneffected_by_spalding(Spalding_transaction.java:298)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cornwall_wallet_balance_remains_and_is_uneffected_by_spalding -->
        <test-method status="FAIL" signature="slough_wallet_balance_remains_and_is_uneffected_by_spalding()[pri:18, instance:Stepdef.Spalding_transaction@2b2948e2]" name="slough_wallet_balance_remains_and_is_uneffected_by_spalding" duration-ms="13347" started-at="2019-09-13T07:52:58Z" finished-at="2019-09-13T07:53:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<9.4> but was:<10.0>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<9.4> but was:<10.0>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Spalding_transaction.slough_wallet_balance_remains_and_is_uneffected_by_spalding(Spalding_transaction.java:338)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- slough_wallet_balance_remains_and_is_uneffected_by_spalding -->
        <test-method status="FAIL" signature="windsor_wallet_balance_remains_and_is_uneffected_by_spalding()[pri:19, instance:Stepdef.Spalding_transaction@2b2948e2]" name="windsor_wallet_balance_remains_and_is_uneffected_by_spalding" duration-ms="15831" started-at="2019-09-13T07:53:11Z" finished-at="2019-09-13T07:53:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<9.4> but was:<10.0>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<9.4> but was:<10.0>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Spalding_transaction.windsor_wallet_balance_remains_and_is_uneffected_by_spalding(Spalding_transaction.java:378)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- windsor_wallet_balance_remains_and_is_uneffected_by_spalding -->
      </class> <!-- Stepdef.Spalding_transaction -->
      <class name="Stepdef.Spalding_register">
        <test-method status="PASS" signature="i_am_not_a_user_of_agate_on_spalding_and_I_open_a_browser(java.lang.String)[pri:0, instance:Stepdef.Spalding_register@210366b4]" name="i_am_not_a_user_of_agate_on_spalding_and_I_open_a_browser" duration-ms="1854" started-at="2019-09-13T07:47:20Z" finished-at="2019-09-13T07:47:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_am_not_a_user_of_agate_on_spalding_and_I_open_a_browser -->
        <test-method status="PASS" signature="i_navigate_to_a_premium_article_on_spalding()[pri:1, instance:Stepdef.Spalding_register@210366b4]" name="i_navigate_to_a_premium_article_on_spalding" duration-ms="11423" started-at="2019-09-13T07:47:22Z" finished-at="2019-09-13T07:47:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_navigate_to_a_premium_article_on_spalding -->
        <test-method status="PASS" signature="i_click_on_the_create_wallet_button_on_spalding()[pri:2, instance:Stepdef.Spalding_register@210366b4]" name="i_click_on_the_create_wallet_button_on_spalding" duration-ms="24361" started-at="2019-09-13T07:47:33Z" finished-at="2019-09-13T07:47:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_click_on_the_create_wallet_button_on_spalding -->
        <test-method status="PASS" signature="i_verify_that_the_create_wallet_button_takes_me_to_the_reg_page_on_spalding()[pri:3, instance:Stepdef.Spalding_register@210366b4]" name="i_verify_that_the_create_wallet_button_takes_me_to_the_reg_page_on_spalding" duration-ms="12036" started-at="2019-09-13T07:47:57Z" finished-at="2019-09-13T07:48:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_verify_that_the_create_wallet_button_takes_me_to_the_reg_page_on_spalding -->
        <test-method status="PASS" signature="i_enter_all_the_details_successfully_on_reg_page_of_spalding()[pri:4, instance:Stepdef.Spalding_register@210366b4]" name="i_enter_all_the_details_successfully_on_reg_page_of_spalding" duration-ms="56608" started-at="2019-09-13T07:48:09Z" finished-at="2019-09-13T07:49:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_enter_all_the_details_successfully_on_reg_page_of_spalding -->
        <test-method status="FAIL" signature="i_am_registered_as_an_agate_user_on_spalding_successfully_and_I_am_shown_a_first_use_notice()[pri:5, instance:Stepdef.Spalding_register@210366b4]" name="i_am_registered_as_an_agate_user_on_spalding_successfully_and_I_am_shown_a_first_use_notice" duration-ms="35534" started-at="2019-09-13T07:49:06Z" finished-at="2019-09-13T07:49:42Z">
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[unknown error: Element <iframe id="iframe__popup_notices" class="" style="display: block; width: 100%; height: 470px; border: none;" cd_frame_id_="fbae885ffb18829a77b03369dee7148f"></iframe> is not clickable at point (432, 320). Other element would receive the click: <div>...</div>
  (Session info: chrome=76.0.3809.132)
  (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.14.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Jayarees-MacBook-Pro.local', ip: 'fe80:0:0:0:1cfe:679:9c1d:9358%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '1.8.0_191'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.43.600229 (3fae4d0cda5334..., userDataDir: /var/folders/s6/h3svzd2j4f3...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:56898}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 76.0.3809.132, webStorageEnabled: true}
Session ID: 270b7c745b7bf657c1566c62b6f28053]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: unknown error: Element <iframe id="iframe__popup_notices" class="" style="display: block; width: 100%; height: 470px; border: none;" cd_frame_id_="fbae885ffb18829a77b03369dee7148f"></iframe> is not clickable at point (432, 320). Other element would receive the click: <div>...</div>
  (Session info: chrome=76.0.3809.132)
  (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.14.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Jayarees-MacBook-Pro.local', ip: 'fe80:0:0:0:1cfe:679:9c1d:9358%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '1.8.0_191'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.43.600229 (3fae4d0cda5334..., userDataDir: /var/folders/s6/h3svzd2j4f3...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:56898}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 76.0.3809.132, webStorageEnabled: true}
Session ID: 270b7c745b7bf657c1566c62b6f28053
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
at Elements.Popbitch_Finish_Notice_elements.Verify_finish_notice_appears(Popbitch_Finish_Notice_elements.java:92)
at Stepdef.Spalding_register.i_am_registered_as_an_agate_user_on_spalding_successfully_and_I_am_shown_a_first_use_notice(Spalding_register.java:160)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_am_registered_as_an_agate_user_on_spalding_successfully_and_I_am_shown_a_first_use_notice -->
      </class> <!-- Stepdef.Spalding_register -->
    </test> <!-- Chrome -->
  </suite> <!-- Chrome -->
</testng-results>
