<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="9" ignored="0" total="20" passed="11">
  <reporter-output>
  </reporter-output>
  <suite name="Chrome" duration-ms="373864" started-at="2019-09-11T16:19:28Z" finished-at="2019-09-11T16:25:42Z">
    <groups>
    </groups>
    <test name="Chrome" duration-ms="373864" started-at="2019-09-11T16:19:28Z" finished-at="2019-09-11T16:25:42Z">
      <class name="Stepdef.Stamford_Login">
        <test-method status="PASS" signature="i_am_a_registered_user_of_stamford_and_I_open_a_browser(java.lang.String)[pri:6, instance:Stepdef.Stamford_Login@eec5a4a]" name="i_am_a_registered_user_of_stamford_and_I_open_a_browser" duration-ms="1419" started-at="2019-09-11T16:21:50Z" finished-at="2019-09-11T16:21:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_am_a_registered_user_of_stamford_and_I_open_a_browser -->
        <test-method status="PASS" signature="i_navigate_to_a_premium_article_on_stamford()[pri:7, instance:Stepdef.Stamford_Login@eec5a4a]" name="i_navigate_to_a_premium_article_on_stamford" duration-ms="12733" started-at="2019-09-11T16:21:51Z" finished-at="2019-09-11T16:22:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_navigate_to_a_premium_article_on_stamford -->
        <test-method status="PASS" signature="i_click_on_Login_from_stamford_First_use_notice()[pri:8, instance:Stepdef.Stamford_Login@eec5a4a]" name="i_click_on_Login_from_stamford_First_use_notice" duration-ms="21429" started-at="2019-09-11T16:22:04Z" finished-at="2019-09-11T16:22:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_click_on_Login_from_stamford_First_use_notice -->
        <test-method status="PASS" signature="i_verify_that_the_Login_Button_Navigates_me_to_the_login_page_to_log_me_in_to_stamford()[pri:9, instance:Stepdef.Stamford_Login@eec5a4a]" name="i_verify_that_the_Login_Button_Navigates_me_to_the_login_page_to_log_me_in_to_stamford" duration-ms="10341" started-at="2019-09-11T16:22:25Z" finished-at="2019-09-11T16:22:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_verify_that_the_Login_Button_Navigates_me_to_the_login_page_to_log_me_in_to_stamford -->
        <test-method status="PASS" signature="entering_the_correct_email_and_password_logs_me_in_to_stamford()[pri:10, instance:Stepdef.Stamford_Login@eec5a4a]" name="entering_the_correct_email_and_password_logs_me_in_to_stamford" duration-ms="7078" started-at="2019-09-11T16:22:36Z" finished-at="2019-09-11T16:22:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- entering_the_correct_email_and_password_logs_me_in_to_stamford -->
        <test-method status="FAIL" signature="verify_that_I_am_being_navigated_to_the_same_article_on_stamford()[pri:11, instance:Stepdef.Stamford_Login@eec5a4a]" name="verify_that_I_am_being_navigated_to_the_same_article_on_stamford" duration-ms="5697" started-at="2019-09-11T16:22:43Z" finished-at="2019-09-11T16:22:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<0.2> but was:<-0.2>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<0.2> but was:<-0.2>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Stamford_Login.verify_that_I_am_being_navigated_to_the_same_article_on_stamford(Stamford_Login.java:187)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify_that_I_am_being_navigated_to_the_same_article_on_stamford -->
      </class> <!-- Stepdef.Stamford_Login -->
      <class name="Stepdef.Stamford_Register">
        <test-method status="PASS" signature="i_am_not_a_user_of_agate_on_stamford_and_I_open_a_browser(java.lang.String)[pri:0, instance:Stepdef.Stamford_Register@210366b4]" name="i_am_not_a_user_of_agate_on_stamford_and_I_open_a_browser" duration-ms="2226" started-at="2019-09-11T16:19:28Z" finished-at="2019-09-11T16:19:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_am_not_a_user_of_agate_on_stamford_and_I_open_a_browser -->
        <test-method status="PASS" signature="i_navigate_to_a_premium_article_on_stamford()[pri:1, instance:Stepdef.Stamford_Register@210366b4]" name="i_navigate_to_a_premium_article_on_stamford" duration-ms="12054" started-at="2019-09-11T16:19:30Z" finished-at="2019-09-11T16:19:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_navigate_to_a_premium_article_on_stamford -->
        <test-method status="PASS" signature="i_click_on_the_create_wallet_button_on_stamford()[pri:2, instance:Stepdef.Stamford_Register@210366b4]" name="i_click_on_the_create_wallet_button_on_stamford" duration-ms="22987" started-at="2019-09-11T16:19:42Z" finished-at="2019-09-11T16:20:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_click_on_the_create_wallet_button_on_stamford -->
        <test-method status="PASS" signature="i_verify_that_the_create_wallet_button_takes_me_to_the_reg_page_on_stamford()[pri:3, instance:Stepdef.Stamford_Register@210366b4]" name="i_verify_that_the_create_wallet_button_takes_me_to_the_reg_page_on_stamford" duration-ms="12036" started-at="2019-09-11T16:20:05Z" finished-at="2019-09-11T16:20:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_verify_that_the_create_wallet_button_takes_me_to_the_reg_page_on_stamford -->
        <test-method status="PASS" signature="i_enter_all_the_details_successfully_on_reg_page_of_stamford()[pri:4, instance:Stepdef.Stamford_Register@210366b4]" name="i_enter_all_the_details_successfully_on_reg_page_of_stamford" duration-ms="56935" started-at="2019-09-11T16:20:17Z" finished-at="2019-09-11T16:21:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_enter_all_the_details_successfully_on_reg_page_of_stamford -->
        <test-method status="FAIL" signature="i_am_registered_as_an_agate_user_on_stamford_successfully_and_I_am_shown_a_first_use_notice()[pri:5, instance:Stepdef.Stamford_Register@210366b4]" name="i_am_registered_as_an_agate_user_on_stamford_successfully_and_I_am_shown_a_first_use_notice" duration-ms="35592" started-at="2019-09-11T16:21:14Z" finished-at="2019-09-11T16:21:50Z">
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[unknown error: Element <iframe id="iframe__popup_notices" class="" style="display: block; width: 100%; height: 470px; border: none;" cd_frame_id_="63dd30c707ba3b3c7612293078222891"></iframe> is not clickable at point (432, 324). Other element would receive the click: <div>...</div>
  (Session info: chrome=76.0.3809.132)
  (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.14.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Jayarees-MacBook-Pro.local', ip: 'fe80:0:0:0:1cfe:679:9c1d:9358%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '1.8.0_191'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.43.600229 (3fae4d0cda5334..., userDataDir: /var/folders/s6/h3svzd2j4f3...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:61900}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 76.0.3809.132, webStorageEnabled: true}
Session ID: cbeaebb2025bdc1b39831b99249027b8]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: unknown error: Element <iframe id="iframe__popup_notices" class="" style="display: block; width: 100%; height: 470px; border: none;" cd_frame_id_="63dd30c707ba3b3c7612293078222891"></iframe> is not clickable at point (432, 324). Other element would receive the click: <div>...</div>
  (Session info: chrome=76.0.3809.132)
  (Driver info: chromedriver=2.43.600229 (3fae4d0cda5334b4f533bede5a4787f7b832d052),platform=Mac OS X 10.14.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'Jayarees-MacBook-Pro.local', ip: 'fe80:0:0:0:1cfe:679:9c1d:9358%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.5', java.version: '1.8.0_191'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.43.600229 (3fae4d0cda5334..., userDataDir: /var/folders/s6/h3svzd2j4f3...}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:61900}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 76.0.3809.132, webStorageEnabled: true}
Session ID: cbeaebb2025bdc1b39831b99249027b8
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
at Elements.Popbitch_Finish_Notice_elements.Verify_finish_notice_appears(Popbitch_Finish_Notice_elements.java:92)
at Stepdef.Stamford_Register.i_am_registered_as_an_agate_user_on_stamford_successfully_and_I_am_shown_a_first_use_notice(Stamford_Register.java:153)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_am_registered_as_an_agate_user_on_stamford_successfully_and_I_am_shown_a_first_use_notice -->
      </class> <!-- Stepdef.Stamford_Register -->
      <class name="Stepdef.Stamford_transaction">
        <test-method status="PASS" signature="i_am_a_registered_Agate_User_and_I_login_in_to_stamford(java.lang.String)[pri:12, instance:Stepdef.Stamford_transaction@2b2948e2]" name="i_am_a_registered_Agate_User_and_I_login_in_to_stamford" duration-ms="69574" started-at="2019-09-11T16:22:48Z" finished-at="2019-09-11T16:23:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_am_a_registered_Agate_User_and_I_login_in_to_stamford -->
        <test-method status="FAIL" signature="i_read_a_premium_article_on_stamford()[pri:13, instance:Stepdef.Stamford_transaction@2b2948e2]" name="i_read_a_premium_article_on_stamford" duration-ms="15458" started-at="2019-09-11T16:23:58Z" finished-at="2019-09-11T16:24:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<0.2> but was:<-0.4>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<0.2> but was:<-0.4>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Stamford_transaction.i_read_a_premium_article_on_stamford(Stamford_transaction.java:140)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- i_read_a_premium_article_on_stamford -->
        <test-method status="FAIL" signature="the_popbitch_wallet_balance_is_updated_same_as_stamford_and_free_point_remains_uneffected()[pri:14, instance:Stepdef.Stamford_transaction@2b2948e2]" name="the_popbitch_wallet_balance_is_updated_same_as_stamford_and_free_point_remains_uneffected" duration-ms="13520" started-at="2019-09-11T16:24:13Z" finished-at="2019-09-11T16:24:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<9.4> but was:<10.0>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<9.4> but was:<10.0>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Stamford_transaction.the_popbitch_wallet_balance_is_updated_same_as_stamford_and_free_point_remains_uneffected(Stamford_transaction.java:180)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- the_popbitch_wallet_balance_is_updated_same_as_stamford_and_free_point_remains_uneffected -->
        <test-method status="FAIL" signature="reaction_wallet_balance_is_updated_and_free_point_remains_uneffected_same_as_stamford()[pri:15, instance:Stepdef.Stamford_transaction@2b2948e2]" name="reaction_wallet_balance_is_updated_and_free_point_remains_uneffected_same_as_stamford" duration-ms="14677" started-at="2019-09-11T16:24:27Z" finished-at="2019-09-11T16:24:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<9.4> but was:<10.0>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<9.4> but was:<10.0>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Stamford_transaction.reaction_wallet_balance_is_updated_and_free_point_remains_uneffected_same_as_stamford(Stamford_transaction.java:220)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reaction_wallet_balance_is_updated_and_free_point_remains_uneffected_same_as_stamford -->
        <test-method status="FAIL" signature="cricketer_wallet_balance_remains_and_is_uneffected_by_stamford()[pri:16, instance:Stepdef.Stamford_transaction@2b2948e2]" name="cricketer_wallet_balance_remains_and_is_uneffected_by_stamford" duration-ms="14781" started-at="2019-09-11T16:24:42Z" finished-at="2019-09-11T16:24:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<9.4> but was:<10.0>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<9.4> but was:<10.0>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Stamford_transaction.cricketer_wallet_balance_remains_and_is_uneffected_by_stamford(Stamford_transaction.java:261)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cricketer_wallet_balance_remains_and_is_uneffected_by_stamford -->
        <test-method status="FAIL" signature="cornwall_wallet_balance_remains_and_is_uneffected_by_stamford()[pri:17, instance:Stepdef.Stamford_transaction@2b2948e2]" name="cornwall_wallet_balance_remains_and_is_uneffected_by_stamford" duration-ms="14575" started-at="2019-09-11T16:24:56Z" finished-at="2019-09-11T16:25:11Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<9.4> but was:<10.0>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<9.4> but was:<10.0>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Stamford_transaction.cornwall_wallet_balance_remains_and_is_uneffected_by_stamford(Stamford_transaction.java:301)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cornwall_wallet_balance_remains_and_is_uneffected_by_stamford -->
        <test-method status="FAIL" signature="slough_wallet_balance_remains_and_is_uneffected_by_stamford()[pri:18, instance:Stepdef.Stamford_transaction@2b2948e2]" name="slough_wallet_balance_remains_and_is_uneffected_by_stamford" duration-ms="13899" started-at="2019-09-11T16:25:11Z" finished-at="2019-09-11T16:25:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<9.4> but was:<10.0>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<9.4> but was:<10.0>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Stamford_transaction.slough_wallet_balance_remains_and_is_uneffected_by_stamford(Stamford_transaction.java:341)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- slough_wallet_balance_remains_and_is_uneffected_by_stamford -->
        <test-method status="FAIL" signature="windsor_wallet_balance_remains_and_is_uneffected_by_stamford()[pri:19, instance:Stepdef.Stamford_transaction@2b2948e2]" name="windsor_wallet_balance_remains_and_is_uneffected_by_stamford" duration-ms="16787" started-at="2019-09-11T16:25:25Z" finished-at="2019-09-11T16:25:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<9.4> but was:<10.0>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<9.4> but was:<10.0>
at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:88)
at Stepdef.Stamford_transaction.windsor_wallet_balance_remains_and_is_uneffected_by_stamford(Stamford_transaction.java:381)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- windsor_wallet_balance_remains_and_is_uneffected_by_stamford -->
      </class> <!-- Stepdef.Stamford_transaction -->
    </test> <!-- Chrome -->
  </suite> <!-- Chrome -->
</testng-results>
